// src/components/footer.svelte
<footer class="subpixel-antialiased p-8 footer bg-footer text-neutral-content bottom-0 fixed">
  <div>
    <svg
      width="50"
      height="50"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill-rule="evenodd"
      clip-rule="evenodd"
      class="fill-current"
    >
      <path
        d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"
      />
    </svg>
    <p class="font-bold text-md">
      Skyblock-Plus
      <br />The best Skyblock Bot on discord
    </p>
    <p class="font-bold text-xs">
      Website made by <a href="https://github.com/TrashCan69420" class="text-red-700"
        >TrashCan#8913</a
      >
    </p>
  </div>
  <div class="font-bold">
    <span class="footer-title">Policy's</span>
    <div class="grid grid-flow-col gap-4">
      <a href="tos">
        <h1>Terms Of Service</h1>
      </a>
      <a href="privacy-policy">
        <h1>privacy policy</h1>
      </a>
    </div>
  </div>
</footer>

// components/Footer.vue
<template>
  <footer class="fixed inset-x-0 w-full bottom-0 pb-3 bg-footer-color">
    <div class="container mx-auto px-4">
      <div
        class="flex flex-wrap items-center md:justify-between justify-center"
      >
        <div class="w-full md:w-4/12 px-4">
          <div class="text-lg text-white font-semibold py-4">
            Copyright © {{ date }} Skyblock Plus
            <div class="text-sm text-white">
              Website made by
              <a class="text-red-600" href="https://github.com/TrashCan69420"
                >TrashCan#8913</a
              >
            </div>
          </div>
        </div>
        <div class="w-full md:w-8/12 px-4">
          <ul class="flex flex-wrap list-none md:justify-end justify-center">
            <l
              class="text-white hover:text-gray-400 text-lg font-semibold block py-1 px-3"
              ><a href="privacy-policy">privacy policy</a></l
            >
            <l
              class="text-white hover:text-gray-400 text-lg font-semibold block py-1 px-3"
              ><a href="terms-of-service">TOS</a></l
            >
          </ul>
        </div>
      </div>
    </div>
  </footer>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "FooterComponent",
  data() {
    return {
      date: new Date().getFullYear(),
    };
  },
});
</script>
